spring.application.name=comic_manga_polica
spring.datasource.url=jdbc:mysql://localhost:3306/manga_comics
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true